import { ToasterProvider } from "@/Components/ToasterProvider";
import { Metadata } from "next";
import "../globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import DashboardLayoutUi from "./_components/DashboardLayoutUi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-900">
        <ToasterProvider />
        <DashboardLayoutUi>{children}</DashboardLayoutUi>
      </body>
    </html>
  );
}
